name: _dotnet-windows-build
on:
  workflow_call:
    inputs:
      dotnet_version:
        required: false
        type: string
        default: '8.0.x'
      project-or-solution:
        required: true
        type: string
      test-project-or-solution:
        required: false
        type: string
        default: ''
      rid:
        type: string
        default: 'win-x86'
      run_tests:
        type: boolean
        default: false
    outputs:
      artifact_name:
        description: "Name of the build output artifact (if produced)"
        value: ${{ jobs.build.outputs.artifact_name }}

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1    

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Restore
        run: dotnet restore "${{ inputs.project-or-solution }}"

      - name: Build
        run: dotnet build "${{ inputs.project-or-solution }}" --configuration Release --no-restore